// ============================================================================
// Nova. (c) 2008 Ken Reed
//
// This module contains the data that is generated by the Nova Console to
// generate a turn (including the very first one). This is the Intel sent to 
// the player.
//
// This is free software. You can redistribute it and/or modify it under the
// terms of the GNU General Public License version 2 as published by the Free
// Software Foundation.
// ============================================================================

using System.Collections;
using System.IO;
using System.Reflection;
using System.Resources;
using System.Runtime.Serialization.Formatters.Binary;
using System.Runtime.Serialization.Formatters;
using System.Runtime.Serialization;
using System;
using System.Drawing;


// ============================================================================
// Manipulation of the turn data that is created by the Nova Console and read
// by the Nova GUI.
// ============================================================================

namespace NovaCommon
{
   [Serializable]
   public sealed class Intel
   {

// ============================================================================
// The data items created by the Nova Console and read by the Nova GUI.
// ============================================================================

      public int       TurnYear      = 2100;
      public ArrayList Messages      = new ArrayList();
      public ArrayList Battles       = new ArrayList();
      public ArrayList AllRaceNames  = new ArrayList();
      public ArrayList AllScores     = new ArrayList();
      public Hashtable RaceIcons     = new Hashtable();
      public Hashtable AllFleets     = new Hashtable();
      public Hashtable AllDesigns    = new Hashtable();
      public Hashtable AllStars      = new Hashtable();
      public Hashtable AllMinefields = new Hashtable();

// ============================================================================
// Data private to this module.
// ============================================================================

      private static Intel      instance  = null;
      private static Object          padlock   = new Object();
      private static BinaryFormatter formatter = new BinaryFormatter();


// ============================================================================
// Private constructor to prevent anyone else creating instances of this class.
// ============================================================================

      private Intel() {}


// ============================================================================
// Provide a mechanism of accessing the single instance of this class that we
// will create locally. Creation of the data is thread-safe.
// ============================================================================

      public static Intel Data
      {
         get {
            lock(padlock) {
               if (instance == null) {
                  instance = new Intel();
               }
               return instance;
            }
         }

         set {
            instance = value;
         }
      }


// ============================================================================
// Reset all data structures.
// ============================================================================

      public void Clear()
      {
         Data.AllDesigns.Clear();
         Data.AllFleets.Clear();
         Data.AllRaceNames.Clear();
         Data.AllStars.Clear();
         Data.AllMinefields.Clear();
         Data.Battles.Clear();
         Data.Messages.Clear();

         TurnYear = 2100;
      }

      // ============================================================================
      // Return an XmlElement representation of the Global Turn Data
      // ============================================================================      
       /*      public XmlElement ToXml(XmlDocument xmldoc)
   {
       System.Xml.XmlElement xmlelModule = xmldoc.CreateElement("Module");


       // CellNumber
       XmlElement xmlelCellNumber = xmldoc.CreateElement("CellNumber");
       XmlText xmltxtCellNumber = xmldoc.CreateTextNode(this.CellNumber.ToString());
       xmlelCellNumber.AppendChild(xmltxtCellNumber);
       xmlelModule.AppendChild(xmlelCellNumber);
       // ComponentCount
       XmlElement xmlelComponentCount = xmldoc.CreateElement("ComponentCount");
       XmlText xmltxtComponentCount = xmldoc.CreateTextNode(this.ComponentCount.ToString());
       xmlelComponentCount.AppendChild(xmltxtComponentCount);
       xmlelModule.AppendChild(xmlelComponentCount);
       // ComponentMaximum
       XmlElement xmlelComponentMaximum = xmldoc.CreateElement("ComponentMaximum");
       XmlText xmltxtComponentMaximum = xmldoc.CreateTextNode(this.ComponentMaximum.ToString());
       xmlelComponentMaximum.AppendChild(xmltxtComponentMaximum);
       xmlelModule.AppendChild(xmlelComponentMaximum);
       // ComponentType
       XmlElement xmlelComponentType = xmldoc.CreateElement("ComponentType");
       XmlText xmltxtComponentType = xmldoc.CreateTextNode(this.ComponentType);
       xmlelComponentType.AppendChild(xmltxtComponentType);
       xmlelModule.AppendChild(xmlelComponentType);

        

       return xmlelModule;
   }  */
   }

}
