// ============================================================================
// Nova. (c) 2008 Ken Reed
//
// This module contains the data that is generated by the Nova GUI and passed
// to the Nova Console so that it can generate the turn for the next year. These
// are the orders sent to the console/server.
//
// This is free software. You can redistribute it and/or modify it under the
// terms of the GNU General Public License version 2 as published by the Free
// Software Foundation.
// ============================================================================

using System.Collections;
using System;


// ============================================================================
// Definition of the orders that are created by the Nova GUI and read by the
// Nova Console.
// ============================================================================

namespace NovaCommon
{
   [Serializable]
   public sealed class Orders
   {
      public ArrayList   RaceFleets      = new ArrayList();
      public ArrayList   RaceDesigns     = new ArrayList();
      public ArrayList   RaceStars       = new ArrayList();
      public ArrayList   DeletedFleets   = new ArrayList();
      public ArrayList   DeletedDesigns  = new ArrayList();
      public RaceData    PlayerData      = new RaceData();
      public int         TechLevel       = 0;
   }
}
