// This file needs -*- c++ -*- mode
// ============================================================================
// Nova. (c) 2008 Ken Reed
//
// This module contains the data that is generated by the Nova GUI and passed
// to the Nova Console so that it can generate the turn for the next year.
//
// This is free software. You can redistribute it and/or modify it under the
// terms of the GNU General Public License version 2 as published by the Free
// Software Foundation.
// ============================================================================

using System;
using System.Collections.Generic;
using System.Text;


// ============================================================================
// Keeps details of the data needed for the Score report
// ============================================================================

namespace NovaCommon
{
   [Serializable]
   public sealed class ScoreRecord :  IComparable
   {
      public string Race;
      public int    Rank;
      public int    Score;
      public int    Planets;
      public int    Starbases;
      public int    UnarmedShips;
      public int    EscortShips;
      public int    CapitalShips;
      public int    TechLevel;
      public int    Resources;


// ============================================================================
// Provide a sort by rank function
// ============================================================================

      public int CompareTo (Object rightHandSide) 
      {
         ScoreRecord rhs = (ScoreRecord) rightHandSide;
         return rhs.Score.CompareTo(this.Score);
      }
   }
}
